version: "3.9"
services:
  backend:
    container_name: backend
    build:
      context: ./backend
    ports:
      - 8080:8080
    depends_on:
      - mongodb
    volumes:
      - ./backend:/app
    env_file:
      - .env

  frontend:
    container_name: frontend
    build:
      context: ./frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend/src:/app/src

  mongodb:
    container_name: mongodb
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=rootpassword
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container:
